vim.pack.add({
  { src = "https://github.com/saghen/blink.cmp",                            version = "v1",                      name = "blink.cmp" },
  { src = "https://github.com/akinsho/bufferline.nvim",                     name = "bufferline" },
  { src = "https://github.com/stevearc/conform.nvim",                       name = "conform" },
  { src = "https://github.com/sindrets/diffview.nvim",                      name = "diffview" },
  { src = "https://github.com/pteroctopus/faster.nvim",                     name = "faster.nvim" },
  { src = "https://github.com/ibhagwan/fzf-lua",                            name = "fzf-lua" },
  { src = "https://github.com/lewis6991/gitsigns.nvim",                     name = "gitsigns" },
  { src = "https://github.com/m4xshen/hardtime.nvim",                       name = "hardtime.nvim" },
  { src = "https://github.com/lukas-reineke/indent-blankline.nvim",         name = "ibl" },
  { src = "https://github.com/mason-org/mason.nvim",                        name = "mason" },
  { src = "https://github.com/nvim-mini/mini.icons",                        name = "mini.icons" },
  { src = "https://github.com/echasnovski/mini.comment",                    name = "mini.comment" },
  { src = "https://github.com/echasnovski/mini.starter",                    name = "mini.starter" },
  { src = "https://github.com/MunifTanjim/nui.nvim",                        name = "nui.nvim" },
  { src = "https://github.com/mfussenegger/nvim-lint",                      name = "lint" },
  { src = "https://github.com/windwp/nvim-autopairs",                       name = "nvim-autopairs" },
  { src = "https://github.com/gpanders/nvim-parinfer",                      name = "nvim-parinfer" },
  { src = "https://github.com/nvim-tree/nvim-tree.lua",                     name = "nvim-tree.lua" },
  { src = "https://github.com/nvim-treesitter/nvim-treesitter",             name = "nvim-treesitter" },
  { src = "https://github.com/nvim-treesitter/nvim-treesitter-context",     name = "nvim-treesitter-context" },
  { src = "https://github.com/nvim-treesitter/nvim-treesitter-textobjects", name = "nvim-treesitter-textobjects" },
  { src = "https://github.com/nvim-tree/nvim-web-devicons",                 name = "nvim-web-devicons" },
  { src = "https://github.com/HiPhish/rainbow-delimiters.nvim",             name = "rainbow-delimiters" },
  { src = "https://github.com/rachartier/tiny-inline-diagnostic.nvim",      name = "tiny-inline-diagnostic.nvim" },
  { src = "https://github.com/folke/trouble.nvim",                          name = "trouble.nvim" },
  { src = "https://github.com/sainnhe/sonokai",                             name = "sonokai" },
}, {
  load = true,
})
